### ISSUE TITLE
WebUSB not detecting keyboard

### ISSUE THREAD

**Issue by ivanperez21** [flathub/org.chromium.Chromium#124]
Manufacturer of ergonomic keyboards ZSA uses a web tool called Oryx to configure various layouts and perform live training. The live training uses Chromium WebUSB to detect the keyboard and provide a geometry based layout representation of keystrokes.

Chromium via flathub does not seem to pick up the keyboard when a webusb is called for. I have my udev rules set up appropriate as I can flash firmware to the device from my OS(PopOS!).
Please see Oryx configuration details here.
https://github.com/zsa/wally/wiki/Live-training-on-Linux

There is a warning that states the following but I am unable to locate this sort of setting in the PopShop that uses flathub.

> WARNING: On the latest Ubuntu versions and its derivatives, browsers are installed via snapd. In the Software Package manager GUI, find your browser's page and click the "Permissions button", then tick the toggle "Access USB hardware directly".

**Comment by Ferenc-** [comment]
This issue is definitely not limited to keyboards.
For easy reproduction, one can clone [this repo](https://github.com/finikorg/webusb-sample/), and add some locally available [vendorId and productId](https://github.com/finikorg/webusb-sample/blob/master/index.html#L22),
that are present on the current system, and then open index.html locally, click on `Connect To WebUSB Device`.
On a non-flatpak chromium, one already gets a list of those recently added devices, but in flatpak that doesn't happen,
I personally didn't manage to get anything listed there.

In theory we already provide [device=all](https://github.com/flathub/org.chromium.Chromium/blob/master/org.chromium.Chromium.yaml#L11), which should be enough to access any hardware device.
Although specific USB support in flatpak is not entirely complete yet https://github.com/flatpak/flatpak/pull/4083 
I don't think that is necessarily needed here.
We know, that using [udev is not an option](https://github.com/flatpak/flatpak/issues/961).
So maybe we should see if chromium is still trying to use libudev, and if there is way to turn that off.
This [patch](https://github.com/flathub/org.chromium.Chromium/blob/master/patches/0016-webusb-Properly-handle-lack-of-platform-support.patch) already tries to avoid some issues around the lack of udev, maybe it's not enough?

**Comment by wjt** [comment]
I think this will have been fixed by a19d2db6a0e89a4c0663c9b662ba4ef309e0fbf2a19d2db6a0e89a4c0663c9b662ba4ef309e0fbf2, at least if you connect the device before launching Chromium – try updating and testing again?

> - Udev is now enabled. Disabling it was a huge mistake on my part, as I
>   was under the impression that it did not work *at all*, whereas in
>   practice, devices can at least be listed (monitoring is what does not
>   work). With this, we should be able to drop the patches related to
>   fixing the WebUSB and WebHID services on no-udev builds.

**Comment by Ferenc-** [comment]
> I think this will have been fixed by a19d2db6a0e89a4c0663c9b662ba4ef309e0fbf2a19d2db6a0e89a4c0663c9b662ba4ef309e0fbf2, at least if you connect the device before launching Chromium – try updating and testing again?
> 
> > * Udev is now enabled. Disabling it was a huge mistake on my part, as I
> >   was under the impression that it did not work _at all_, whereas in
> >   practice, devices can at least be listed (monitoring is what does not
> >   work). With this, we should be able to drop the patches related to
> >   fixing the WebUSB and WebHID services on no-udev builds.

Thanks for the heads up! My previous test case is suddenly working!

**Comment by rothn** [comment]
I am still having the issue with Version 117.0.5938.88 (Official Build) snap (64-bit)
